### ISSUE TITLE
pyplanet build is failing

### ISSUE THREAD

**Issue by ineentho** [Harha/trackmania-server-docker#3]
Hello!

First of, I appreciate that you took the time to put together these docker images (and even document them)!

pyplanet released a new version a few days ago (0.9.9) which is available on PyPi, but no updated docker image has been built for it.

Of course I can work around that by building my own version for now, but I'd be nice if you could check why the automated build isn't working. I noticed that the latest commit is failing to build, but I can't access the logs on docker hub, so I don't know if that's actually the issue.

**Comment by Harha** [comment]
Hey!

Thanks for the info, I don't get any notifications about fails so that's why I haven't noticed. I'll check what's wrong...

**Comment by Harha** [comment]
There's something weird going on with the docker image builder machine and pyplanet pip package dependencies. The build seems to sometimes fail and sometimes pass on dockerhub, when it fails, it fails when installing "cryptography".

`
Running setup.py bdist_wheel for cryptography: started  
Running setup.py bdist_wheel for cryptography: finished with status "error"
`

When it does not fail, it does not even need to run that step, meaning cryptography wheel was already built for the architecture. I don't understand this non-deterministic behavior, but I'm going to say that we have to either provide the libraries and whatnot for the builder machine to be able to build cryptography-package, or we investigate why it sometimes tries to build that in the first place.

The build fails here: `error: Can not find Rust compiler` - But the error also suggests that `If you are experiencing issues with Rust for *this release only* you may
set the environment variable `CRYPTOGRAPHY_DONT_BUILD_RUST=1`.` - I don't want to provide a rust compiler into the image, so I think I'll set that environment variable to true and see if it stops failing then...

**Comment by Harha** [comment]
I did some changes. Let's see if the build starts working properly now too. There is already an updated image in dockerhub too for pyplanet image. I also deleted the build-legacy files, it seems that barely anyone used that image, so it's better to get rid of it.

Now the pyplanet image uses latest python 3.8 debian-buster image as base image, the errors suggested that we should use up-to-date python and pip and since the old build steps installed python3 via debian packages it was most certainly not up-to-date at all since debian is such a static distro when it comes to packages.

**Comment by Harha** [comment]
Well the build passes now, but it didn't build cryptography since it was able to use the pre-built wheel binaries for it. I don't understand why it sometimes tried to build it, since those binaries should always be available...

Anyways, I'll close the issue now since it works again. ¯\_(ツ)_/¯

**Comment by ineentho** [comment]
Thanks for the fix, I'm glad you figured something out 🙂

**Comment by ineentho** [comment]
@Harha Hello! Sorry to bother, but this seems to be happening again. The last pyplanet build was released on Mar 22nd, but no build has been made since then.

Is there any way you could make the build logs from dockerhub public? If so, I'd gladly take a look at attempt to make a PR

**Comment by Harha** [comment]
@ineentho I'll create a new issue on github about that. The problem here is that I haven't had time to create a script that checks if pyplanet gets updated, so currently the only time the images are rebuilt automatically is when TM2020 server latest zip is updated.

But I'll see if I can make the logs public too, it would be better to have them public anyways.

https://github.com/Harha/trackmania-server-docker/issues/4
